FROM tomcat:9.0.73-jdk17

RUN apt-get update; apt-get -y upgrade

RUN apt-get -y install tar
RUN apt-get -y install unzip
RUN apt-get -y install git
RUN apt-get -y install jq
RUN apt-get -y install vim